include: package:all_lint_rules_community/all.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    deprecated_member_use_from_same_package: ignore
    parameter_assignments: warning
    todo: ignore

linter:
  rules:
    prefer_double_quotes: false
    prefer_single_quotes: false
    prefer_final_locals: true
    prefer_final_parameters: false
    unnecessary_final: false
    always_specify_types: false
    prefer_expression_function_bodies: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    diagnostic_describe_all_properties: false
    prefer_relative_imports: false
    library_prefixes: false
    one_member_abstracts: false