// Mocks generated by Mockito 5.1.0 from annotations
// in todo_clean/test/features/todo/domain/usecases/get_todos_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_clean/core/error/failures.dart' as _i3;
import 'package:todo_clean/features/todo/domain/entities/todo.dart' as _i6;
import 'package:todo_clean/features/todo/domain/repositories/todo_repository_interface.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeFailure_1 extends _i1.Fake implements _i3.Failure {}

/// A class which mocks [TodoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRepository extends _i1.Mock implements _i4.ITodoRepository {
  MockTodoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<List<_i6.Todo>, _i3.Failure>> getTodos() =>
      (super.noSuchMethod(Invocation.method(#getTodos, []),
          returnValue: Future<_i2.Either<List<_i6.Todo>, _i3.Failure>>.value(
              _FakeEither_0<List<_i6.Todo>, _i3.Failure>())) as _i5
          .Future<_i2.Either<List<_i6.Todo>, _i3.Failure>>);
  @override
  _i5.Future<_i2.Either<_i6.Todo, _i3.Failure>> addTodo(_i6.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#addTodo, [todo]),
              returnValue: Future<_i2.Either<_i6.Todo, _i3.Failure>>.value(
                  _FakeEither_0<_i6.Todo, _i3.Failure>()))
          as _i5.Future<_i2.Either<_i6.Todo, _i3.Failure>>);
  @override
  _i5.Future<_i3.Failure> deleteTodo(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteTodo, [id]),
              returnValue: Future<_i3.Failure>.value(_FakeFailure_1()))
          as _i5.Future<_i3.Failure>);
  @override
  _i5.Future<_i2.Either<_i6.Todo, _i3.Failure>> markCompleted(int? id) =>
      (super.noSuchMethod(Invocation.method(#markCompleted, [id]),
              returnValue: Future<_i2.Either<_i6.Todo, _i3.Failure>>.value(
                  _FakeEither_0<_i6.Todo, _i3.Failure>()))
          as _i5.Future<_i2.Either<_i6.Todo, _i3.Failure>>);
}
