// Mocks generated by Mockito 5.1.0 from annotations
// in todo_clean/test/features/todo/data/repositories/todo_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_clean/core/network/network_info.dart' as _i8;
import 'package:todo_clean/features/todo/data/local_datasources/todo_db.dart' as _i6;
import 'package:todo_clean/features/todo/data/local_datasources/todo_local_datascource.dart' as _i5;
import 'package:todo_clean/features/todo/data/remote_datasources/todo_raw.dart' as _i4;
import 'package:todo_clean/features/todo/data/remote_datasources/todo_remote_datasource.dart'
    as _i2;
import 'package:todo_clean/features/todo/domain/entities/todo.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ITodoRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITodoRemoteDatasource extends _i1.Mock implements _i2.ITodoRemoteDatasource {
  MockITodoRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TodoRaw>> getTodos() => (super.noSuchMethod(Invocation.method(#getTodos, []),
          returnValue: Future<List<_i4.TodoRaw>>.value(<_i4.TodoRaw>[]))
      as _i3.Future<List<_i4.TodoRaw>>);
}

/// A class which mocks [ITodoLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockITodoLocalDatasource extends _i1.Mock implements _i5.ITodoLocalDatasource {
  MockITodoLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i6.TodoDb>> getTodos() => (super.noSuchMethod(Invocation.method(#getTodos, []),
      returnValue: Stream<List<_i6.TodoDb>>.empty()) as _i3.Stream<List<_i6.TodoDb>>);
  @override
  _i3.Future<void> saveTodos(List<_i7.Todo>? todos) =>
      (super.noSuchMethod(Invocation.method(#saveTodos, [todos]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> saveTodo(_i7.Todo? todo) =>
      (super.noSuchMethod(Invocation.method(#saveTodo, [todo]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}

/// A class which mocks [INetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockINetworkInfo extends _i1.Mock implements _i8.INetworkInfo {
  MockINetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: Future<bool>.value(false))
          as _i3.Future<bool>);
}
