// Mocks generated by Mockito 5.1.0 from annotations
// in todo_clean/test/features/todo/presentation/bloc/todos_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:todo_clean/core/error/failures.dart' as _i7;
import 'package:todo_clean/core/usecases/use_case_interface.dart' as _i8;
import 'package:todo_clean/features/todo/domain/entities/todo.dart' as _i6;
import 'package:todo_clean/features/todo/domain/repositories/todo_repository_interface.dart'
    as _i2;
import 'package:todo_clean/features/todo/domain/usecases/get_todos_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeITodoRepository_0 extends _i1.Fake implements _i2.ITodoRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetTodosUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTodosUsecase extends _i1.Mock implements _i4.GetTodosUsecase {
  MockGetTodosUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ITodoRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeITodoRepository_0()) as _i2.ITodoRepository);
  @override
  _i5.Future<_i3.Either<List<_i6.Todo>, _i7.Failure>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
          returnValue: Future<_i3.Either<List<_i6.Todo>, _i7.Failure>>.value(
              _FakeEither_1<List<_i6.Todo>, _i7.Failure>())) as _i5
          .Future<_i3.Either<List<_i6.Todo>, _i7.Failure>>);
}
